repos:
  - repo: builtin
    hooks:
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        language: system
        entry: cargo fmt
        files: ^src/.*\.rs$
        pass_filenames: false
