# host = "127.0.0.1"
# port = 4728
# system_prompt = "You are Rika, a helpful personal AI assistant."
# temperature = 0.1

provider = "openai"
model = "gpt-5.2"

workspace_dir = "./workspace"

[providers.openrouter]
# api_key = "xxx"
# Or use an environment variable:
env_key = "OPENROUTER_API_KEY"

[providers.openai]
# base_url = "https://api.openai.com/v1"
base_url = "http://localhost:8317/v1"
api_key = "xxx"

# [skills]
# enabled = true

# [prompt]
# bootstrap_max_chars = 20000 # default: 20000
# bootstrap_total_max_chars = 150000 # default: 150000

# [mcp]
# enabled = true # default: true

# [[mcp.servers]]
# name = "filesystem"
# transport = "stdio" # default: "stdio"
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-filesystem", "/tmp"]
# tool_timeout_secs = 180 # default: 180, max: 600
# init_timeout_secs = 30 # default: 30
# enabled = true # default: true

# [[mcp.servers]]
# name = "linear"
# transport = "http" # default: "stdio"
# url = "https://mcp.linear.app/mcp"
# headers = { Authorization = "Bearer ${LINEAR_MCP_TOKEN}" }
# tool_timeout_secs = 180 # default: 180, max: 600
# init_timeout_secs = 30 # default: 30
# enabled = true # default: true
