[tools]
bun = "1.3"
rust = "stable"
watchexec = "latest"
prek = "latest"
prettier = "latest"

[env]
RUST_LOG = "info"
# RUSTFLAGS = "-Awarnings"

[hooks]
postinstall = '''
prek install --overwrite
mise run install:*
'''

[tasks."install:fe"]
dir = "{{cwd}}/web"
run = "bun install"
[tasks."install:be"]
run = "cargo build"

[tasks."dev:be"]
env = { RIKA_DEV_MODE = "1", RIKA_DEV_CORS_ORIGINS = "http://localhost:3000,http://127.0.0.1:3000" }
run = "watchexec --restart --exts rs,toml -- cargo run -- start --foreground"
[tasks."dev:fe"]
env = { RIKA_DEV_MODE = "1", RIKA_DEV_BACKEND_WS_HOSTPORT = "127.0.0.1:4728" }
dir = "{{cwd}}/web"
run = "watchexec --clear --restart --exts html,css,ts,tsx -- bun run dev"

[tasks."build:be"]
run = "cargo build --locked"
[tasks."build:fe"]
dir = "{{cwd}}/web"
run = "bun run build"

[tasks."test:be"]
run = "cargo test"
